import { vi } from 'vitest';
import { initialSettings } from '../initialData';

export function createMockStore(overrides: Record<string, unknown> = {}) {
  return {
    t: (k: string) => k,
    bridge: { status: 'disconnected' as const, version: '', pid: 0, uptime: 0, speedLimit: null },
    workspaceView: 'all' as const,
    setWorkspaceView: vi.fn(),
    tasks: [] as any[],
    openDialog: vi.fn(),
    addToast: vi.fn(),
    settings: initialSettings,
    themeSettings: {
      theme: 'dark' as const,
      density: 'normal' as const,
      accent: 'blue' as const,
      sidebar: 'expanded' as const,
      progress: 'bar' as const,
      contrast: 'normal' as const,
      motion: 'enabled' as const,
      blur: 'enabled' as const,
    },
    toasts: [] as any[],
    removeToast: vi.fn(),
    searchQuery: '',
    setSearchQuery: vi.fn(),
    selectedTaskId: null,
    setSelectedTaskId: vi.fn(),
    isLoading: false,
    dialog: { active: null, payload: null },
    queues: [] as any[],
    isDegradedMode: false,
    isNotificationsMuted: false,
    setIsNotificationsMuted: vi.fn(),
    updatingTaskId: null,
    setUpdatingTaskId: vi.fn(),
    activeProgressMinimizedToTaskbar: false,
    setActiveProgressMinimizedToTaskbar: vi.fn(),
    minimizedProgressTask: null,
    setMinimizedProgressTask: vi.fn(),
    pauseTask: vi.fn(), resumeTask: vi.fn(), deleteTask: vi.fn(),
    updateTaskProperties: vi.fn(), updateQueue: vi.fn(), addQueue: vi.fn(),
    deleteQueue: vi.fn(), removeTaskFromQueue: vi.fn(), moveTaskToQueue: vi.fn(),
    createQueueAndMoveTask: vi.fn(), updateSettings: vi.fn(), updateThemeSettings: vi.fn(),
    closeDialog: vi.fn(), triggerBatchDownload: vi.fn(),
    ...overrides,
  };
}
