import { vi } from 'vitest';
import { initialSettings } from '../initialData';

const T_MAP: Record<string, string> = {
  lang_name: 'English',
  app_name: 'NOVA Download Manager',
  status_downloading: 'Downloading',
  status_completed: 'Completed',
  status_paused: 'Paused',
  status_error: 'Error',
  status_queued: 'Queued',
  no_downloads: 'No Downloads',
  nav_properties: 'Properties',
  nav_settings: 'Settings',
  nav_browser_integration: 'Browser Integration',
  resume: 'Resume',
  topbar_stop: 'Stop',
  menu_retry_download: 'Retry Download',
  menu_open_file: 'Open File',
  menu_open_file_location: 'Open File Location',
  menu_copy_url: 'Copy URL',
  action_delete: 'Delete',
  telegram_send_selected_file: 'Send to Telegram',
  telegram_send_file_title: 'Send File',
  telegram_send_file_no_file: 'No file to send.',
  telegram_send_file_ok: 'File sent successfully.',
  telegram_send_file_failed: 'Failed to send file.',
  prio_high: 'High',
  prio_low: 'Low',
  prio_normal: 'Normal',
  table_auto: 'Auto',
  table_customize_columns: 'Customize columns',
  table_batch_delete_confirm: 'Delete {count} selected downloads?',
  engine_task_blocked: 'Engine is unavailable for this task.',
  statusbar_speed_tip: 'Download speed',
  statusbar_counts_tip: 'Active and total download counts',
  statusbar_daemon_tip: 'Daemon is connected',
  statusbar_daemon_title: 'Daemon',
  statusbar_daemon_ok: 'Daemon is connected and healthy.',
  statusbar_degraded_tip: 'Daemon is disconnected \u2014 some features unavailable',
  statusbar_degraded_title: 'Degraded Mode',
  statusbar_degraded_desc: 'Daemon is offline',
  statusbar_downloaded_tip: 'Total downloaded data',
  statusbar_downloaded: 'Downloaded',
  statusbar_of: 'of',
  statusbar_active: 'Active:',
  statusbar_total: 'Total:',
  statusbar_restore_progress_tip: 'Restore progress window',
  statusbar_notifications_title: 'Notifications',
  statusbar_notifications_on: 'Notifications enabled.',
  statusbar_notifications_off: 'Notifications muted.',
  statusbar_notifications_active_tip: 'Notifications active \u2014 click to mute',
  statusbar_notifications_muted_tip: 'Notifications are muted \u2014 click to unmute',
  statusbar_speed_limit: 'Speed Limit',
  statusbar_speed_current: 'Current:',
  statusbar_enable_limiter: 'Enable Limiter',
  statusbar_custom_speed: 'Set custom speed...',
  statusbar_speed_kb_ph: 'Speed KB/s',
  statusbar_speed_mb_ph: 'Speed MB/s',
  statusbar_apply: 'Apply',
  statusbar_telegram_menu: 'Telegram Controls',
  statusbar_telegram_enable: 'Enable Telegram',
  statusbar_telegram_disable: 'Disable Telegram',
  statusbar_telegram_connected: 'Telegram is connected',
  statusbar_telegram_disconnected: 'Telegram is not configured',
  statusbar_clipboard_on: 'Clipboard monitoring is on',
  statusbar_clipboard_off: 'Clipboard monitoring is off',
  engine_caps_loading: 'Engine capabilities are still loading...',
  engine_no_engine: 'No download engine is available.',
  engine_direct_title: 'Direct Engine',
  engine_direct_ready: 'Engine ready for direct downloads',
  engine_direct_unavailable: 'Direct download engine unavailable',
  engine_media_title: 'Media Engine',
  engine_media_ready: 'Engine ready for media downloads',
  engine_media_unavailable: 'Media download engine unavailable',
  engine_ffmpeg_ready: 'FFmpeg is ready for post-processing',
  engine_ffmpeg_unavailable: 'FFmpeg is not available',
  engine_unavailable_desc: 'The required download engine is not ready.',
  speed_limiter: 'Speed Limiter',
  settings_tg_send_test: 'Send Test Notification',
  settings_toast_telegram_test: 'Telegram Test',
  settings_toast_telegram_ok: 'Telegram test successful.',
  settings_toast_telegram_fail: 'Telegram test failed.',
  table_selected_count: '{count} selected',
  cat_programs: 'Programs',
  cat_archives: 'Archives',
  cat_video: 'Video',
  cat_audio: 'Audio',
  cat_documents: 'Documents',
  cat_other: 'Other',
  col_name: 'File Name',
  col_size: 'Size',
  col_status: 'Status',
  col_progress: 'Progress',
  col_speed: 'Speed',
  col_time_left: 'Time Left',
  col_date_added: 'Date Added',
  col_retries: 'Retries',
  col_threads: 'Connections',
  col_priority: 'Priority',
  col_date_completed: 'Completed Date',
  prop_url: 'Source URL',
  prop_type: 'Smart Category',
  btn_cancel: 'Cancel',
  all_downloads: 'All Downloads',
  download_lists: 'Download Lists',
  downloading: 'Downloading',
  completed: 'Completed',
  queued_downloads: 'Queued',
  categories: 'Categories',
  compressed: 'Compressed',
  programs: 'Programs',
  set_theme_mode: 'Theme',
  set_theme_density: 'Density',
  set_theme_density_compact: 'Compact',
  set_theme_density_comfortable: 'Comfortable',
  set_theme_mode_dark: 'Dark',
  set_theme_mode_light: 'Light',
  accent_blue: 'Blue',
  accent_emerald: 'Emerald',
  accent_amber: 'Amber',
  accent_crimson: 'Crimson',
  accent_violet: 'Violet',
  daemon_bridge_connected: 'Connected',
  daemon_bridge_disconnected: 'Disconnected',
};

export function createMockStore(overrides: Record<string, unknown> = {}) {
  return {
    t: (k: string, params?: Record<string, string | number>) => {
      let val = T_MAP[k];
      if (val === undefined) return k;
      if (params) {
        for (const [key, value] of Object.entries(params)) {
          val = val.replace(`{${key}}`, String(value));
        }
      }
      return val;
    },
    bridge: { status: 'disconnected' as const, version: '', pid: 0, uptime: 0, speedLimit: null },
    workspaceView: 'all' as const,
    setWorkspaceView: vi.fn(),
    tasks: [],
    openDialog: vi.fn(),
    addToast: vi.fn(),
    settings: initialSettings,
    themeSettings: {
      theme: 'dark' as const,
      density: 'normal' as const,
      accent: 'blue' as const,
      sidebar: 'expanded' as const,
      progress: 'bar' as const,
      contrast: 'normal' as const,
      motion: 'enabled' as const,
      blur: 'enabled' as const,
    },
    toasts: [],
    removeToast: vi.fn(),
    searchQuery: '',
    setSearchQuery: vi.fn(),
    selectedTaskId: null,
    setSelectedTaskId: vi.fn(),
    isLoading: false,
    dialog: { active: null, payload: null },
    activePage: 'downloads' as const,
    setActivePage: vi.fn(),
    queues: [],
    isDegradedMode: false,
    isNotificationsMuted: false,
    setIsNotificationsMuted: vi.fn(),
    updatingTaskId: null,
    setUpdatingTaskId: vi.fn(),
    activeProgressMinimizedToTaskbar: false,
    setActiveProgressMinimizedToTaskbar: vi.fn(),
    minimizedProgressTask: null,
    setMinimizedProgressTask: vi.fn(),
    addTask: vi.fn(),
    pauseTask: vi.fn(),
    resumeTask: vi.fn(),
    deleteTask: vi.fn(),
    updateTaskProperties: vi.fn(),
    updateQueue: vi.fn(),
    addQueue: vi.fn(),
    deleteQueue: vi.fn(),
    removeTaskFromQueue: vi.fn(),
    moveTaskToQueue: vi.fn(),
    createQueueAndMoveTask: vi.fn(),
    updateSettings: vi.fn(),
    updateThemeSettings: vi.fn(),
    closeDialog: vi.fn(),
    triggerBatchDownload: vi.fn(),
    ...overrides,
  };
}
