export const MAX_HANDOFF_CANDIDATES = 100;
export const MAX_HANDOFF_PAYLOAD_BYTES = 1_500_000;
export const MAX_CANDIDATE_URL_CHARS = 8_192;
export const MAX_CANDIDATE_VARIANTS = 200;
export const MAX_CANDIDATE_SUBTITLES = 200;
export const MAX_TASK_ID_CHARS = 256;

export const MAX_SCAN_REQUESTS_PER_TAB_PER_MINUTE = 12;
export const MAX_SCAN_HTML_CHARS = 700_000;
export const MAX_SCAN_LINKS = 2_000;
export const MAX_SCAN_MEDIA = 1_000;
export const MAX_SCAN_OPEN_GRAPH = 200;
export const MAX_SCAN_JSON_LD_ITEMS = 50;
export const MAX_SCAN_JSON_LD_SCRIPT_CHARS = 120_000;
export const MAX_SCAN_JSON_LD_TOTAL_CHARS = 250_000;

export const MAX_SITE_RULES = 500;
export const MAX_SITE_RULE_HOST_CHARS = 253;
export const MAX_SITE_RULE_PATTERNS = 100;
export const MAX_SITE_RULE_PATTERN_CHARS = 512;

export const MAX_OUTBOX_JOBS = 1_000;
export const OUTBOX_SENT_RETENTION_DAYS = 7;
export const OUTBOX_DEAD_LETTER_RETENTION_DAYS = 30;

export const MAX_EVENT_MESSAGE_BYTES = 256_000;
export const MAX_SSE_BUFFER_BYTES = 512_000;
export const MAX_EVENT_PARSE_ERRORS_PER_CONNECTION = 20;
// Event stream is considered stale (silent drop) when no heartbeat arrives within this window.
export const EVENT_STREAM_STALE_MS = 90_000;
export const MAX_HTTP_REQUEST_PAYLOAD_BYTES = 2_000_000;
export const MAX_HTTP_RESPONSE_BYTES = 2_000_000;
export const MAX_NATIVE_MESSAGE_BYTES = 1_000_000;
export const IDEMPOTENCY_SCHEMA_VERSION = 2;

export const MAX_CANDIDATE_CACHE_TABS = 100;
export const MAX_CANDIDATES_PER_TAB = 250;
export const MAX_CANDIDATE_CACHE_BYTES_PER_TAB = 900_000;
export const MAX_CANDIDATE_METADATA_BYTES = 32_000;
export const MAX_SETTINGS_IMPORT_BYTES = 500_000;
export const MAX_SITE_RULES_IMPORT_BYTES = 500_000;
export const MAX_DIAGNOSTICS_EXPORT_BYTES = 750_000;


export const MAX_RUNTIME_MESSAGE_BYTES = 2_000_000;


export const AGGRESSIVE_MAX_SCAN_HTML_CHARS = 1_500_000;
export const AGGRESSIVE_MAX_SCAN_LINKS = 8_000;
export const AGGRESSIVE_MAX_SCAN_MEDIA = 3_000;
export const AGGRESSIVE_MAX_SCAN_OPEN_GRAPH = 800;
export const AGGRESSIVE_MAX_SCAN_JSON_LD_ITEMS = 200;
export const AGGRESSIVE_MAX_SCAN_JSON_LD_SCRIPT_CHARS = 250_000;
export const AGGRESSIVE_MAX_SCAN_JSON_LD_TOTAL_CHARS = 800_000;
export const AGGRESSIVE_MAX_SCAN_REQUESTS_PER_TAB_PER_MINUTE = 30;
