// Generated by scripts/generate-design-tokens.mjs from nova-design-tokens.json.
package com.nova.downloadmanager.design

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object NOVADesignTokens {
    const val LightWindow: Long = 0xFFF4F6F8L
    const val LightSidebar: Long = 0xFFFFFFFFL
    const val LightSurface: Long = 0xFFFFFFFFL
    const val LightSurfaceHover: Long = 0xFFEDF2F7L
    const val LightSurfaceSelected: Long = 0xFFDFE9F8L
    const val LightSurfaceRaised: Long = 0xFFF8FAFCL
    const val LightBorder: Long = 0xFFD9E0E8L
    const val LightBorderStrong: Long = 0xFFAEB9C6L
    const val LightTextPrimary: Long = 0xFF18212CL
    const val LightTextSecondary: Long = 0xFF4D5B6BL
    const val LightTextMuted: Long = 0xFF627187L
    const val LightAccent: Long = 0xFF168DF7L
    const val LightAccentMuted: Long = 0xFFDCE9FFL
    const val LightSuccess: Long = 0xFF188038L
    const val LightWarning: Long = 0xFF9A6700L
    const val LightDanger: Long = 0xFFC62828L
    const val LightInfo: Long = 0xFF0061A4L
    const val LightFocusRing: Long = 0xFF168DF7L
    const val LightOnAccent: Long = 0xFFFFFFFFL
    const val DarkWindow: Long = 0xFF0D1015L
    const val DarkSidebar: Long = 0xFF11151BL
    const val DarkSurface: Long = 0xFF151A21L
    const val DarkSurfaceHover: Long = 0xFF1B222CL
    const val DarkSurfaceSelected: Long = 0xFF202A38L
    const val DarkSurfaceRaised: Long = 0xFF1A2029L
    const val DarkBorder: Long = 0xFF28313DL
    const val DarkBorderStrong: Long = 0xFF394657L
    const val DarkTextPrimary: Long = 0xFFF3F6FAL
    const val DarkTextSecondary: Long = 0xFFA8B1BDL
    const val DarkTextMuted: Long = 0xFF7F8B9BL
    const val DarkAccent: Long = 0xFF168DF7L
    const val DarkAccentMuted: Long = 0xFF20345AL
    const val DarkSuccess: Long = 0xFF3FB950L
    const val DarkWarning: Long = 0xFFD29922L
    const val DarkDanger: Long = 0xFFF85149L
    const val DarkInfo: Long = 0xFF58A6FFL
    const val DarkFocusRing: Long = 0xFF168DF7L
    const val DarkOnAccent: Long = 0xFFFFFFFFL
    const val HighContrastLightWindow: Long = 0xFFFFFFFFL
    const val HighContrastLightSidebar: Long = 0xFFF7F7F7L
    const val HighContrastLightSurface: Long = 0xFFFFFFFFL
    const val HighContrastLightSurfaceHover: Long = 0xFFE8E8E8L
    const val HighContrastLightSurfaceSelected: Long = 0xFFDEDEDEL
    const val HighContrastLightSurfaceRaised: Long = 0xFFFAFAFAL
    const val HighContrastLightBorder: Long = 0xFF000000L
    const val HighContrastLightBorderStrong: Long = 0xFF000000L
    const val HighContrastLightTextPrimary: Long = 0xFF000000L
    const val HighContrastLightTextSecondary: Long = 0xFF171717L
    const val HighContrastLightTextMuted: Long = 0xFF303030L
    const val HighContrastLightAccent: Long = 0xFF0047B3L
    const val HighContrastLightAccentMuted: Long = 0xFFD5E4FFL
    const val HighContrastLightSuccess: Long = 0xFF006400L
    const val HighContrastLightWarning: Long = 0xFF754C00L
    const val HighContrastLightDanger: Long = 0xFFB00020L
    const val HighContrastLightInfo: Long = 0xFF004C99L
    const val HighContrastLightFocusRing: Long = 0xFF0047B3L
    const val HighContrastLightOnAccent: Long = 0xFFFFFFFFL
    const val HighContrastDarkWindow: Long = 0xFF000000L
    const val HighContrastDarkSidebar: Long = 0xFF050505L
    const val HighContrastDarkSurface: Long = 0xFF0A0A0AL
    const val HighContrastDarkSurfaceHover: Long = 0xFF202020L
    const val HighContrastDarkSurfaceSelected: Long = 0xFF282828L
    const val HighContrastDarkSurfaceRaised: Long = 0xFF101010L
    const val HighContrastDarkBorder: Long = 0xFFFFFFFFL
    const val HighContrastDarkBorderStrong: Long = 0xFFFFFFFFL
    const val HighContrastDarkTextPrimary: Long = 0xFFFFFFFFL
    const val HighContrastDarkTextSecondary: Long = 0xFFF0F0F0L
    const val HighContrastDarkTextMuted: Long = 0xFFD0D0D0L
    const val HighContrastDarkAccent: Long = 0xFF66A3FFL
    const val HighContrastDarkAccentMuted: Long = 0xFF173D70L
    const val HighContrastDarkSuccess: Long = 0xFF66FF66L
    const val HighContrastDarkWarning: Long = 0xFFFFDF66L
    const val HighContrastDarkDanger: Long = 0xFFFF6B6BL
    const val HighContrastDarkInfo: Long = 0xFF80C7FFL
    const val HighContrastDarkFocusRing: Long = 0xFF66A3FFL
    const val HighContrastDarkOnAccent: Long = 0xFF000000L

    val ScreenHorizontal = 20.dp
    val Section = 24.dp
    val ItemGap = 12.dp
    val CompactGap = 8.dp
    val MinimumTouchTarget = 48.dp
    val RadiusExtraSmall = 8.dp
    val RadiusSmall = 12.dp
    val RadiusMedium = 16.dp
    val RadiusLarge = 24.dp
    val RadiusExtraLarge = 28.dp
    val FontTiny = 9.sp
    val FontSmall = 10.sp
    val FontBody = 14.sp
    val FontMedium = 16.sp
    val FontTitle = 22.sp
    val FontHeadline = 24.sp
    const val MotionFastMillis: Int = 100
    const val MotionNormalMillis: Int = 180
    const val MotionStandardMillis: Int = 250

    object IconSemantics {
        const val Downloads: String = "downloads"
        const val AddDownload: String = "addDownload"
        const val Queue: String = "queue"
        const val Settings: String = "settings"
        const val Browser: String = "browser"
        const val Media: String = "media"
        const val Diagnostics: String = "diagnostics"
        const val Share: String = "share"
        const val Dismiss: String = "dismiss"
    }
}
