import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LANGUAGE_METADATA } from '../src/lib/i18n/languageMetadata.ts';
import { loadDict } from './i18n-dicts.mjs';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const RES_DIR = join(ROOT, 'android', 'app', 'src', 'main', 'res');
const CHECK_ONLY = process.argv.includes('--check');

/**
 * Android-visible copy is sourced from NOVA's validated desktop catalog.
 * Adding an entry here requires an existing translation in every language;
 * this generator deliberately emits no English fallback.
 */
const RESOURCE_KEYS = {
  app_name: 'app_name',
  nova_navigation_downloads: 'all_downloads',
  nova_navigation_queue: 'queued_downloads',
  nova_navigation_browser: 'sidebar_web_browser',
  nova_navigation_settings: 'nav_settings',
  nova_filter_all: 'ui_all',
  nova_filter_active: 'active_indicator',
  nova_filter_queue: 'status_queued',
  nova_filter_completed: 'status_completed',
  nova_status_paused: 'status_paused',
  nova_status_error: 'status_error',
  nova_action_add_download: 'add_download',
  nova_action_add_queue: 'action_add_queue',
  nova_action_cancel: 'btn_cancel',
  nova_action_close: 'btn_close',
  nova_action_save: 'btn_save',
  nova_action_apply: 'btn_apply',
  nova_action_clear: 'settings_logging_clear',
  nova_action_refresh: 'settings_logging_refresh',
  nova_action_remove: 'action_delete',
  nova_download_url: 'add_dl_url',
  nova_download_paste_clipboard: 'add_dl_paste_clipboard',
  nova_download_invalid_url: 'add_dl_enter_valid_link',
  nova_download_start_now: 'add_dl_start_now',
  nova_download_queue_only: 'add_dl_queue_only',
  nova_download_empty_title: 'all_downloads',
  nova_download_empty_detail: 'browser_desc',
  nova_download_captured: 'add_dl_queue',
  nova_download_unavailable: 'add_dl_direct_engine_unavailable',
  nova_browser_title: 'browser_title',
  nova_browser_detail: 'browser_desc',
  nova_browser_address: 'grabber_url_label',
  nova_browser_clean_browsing: 'settings_security_privacy',
  nova_browser_capture: 'browser_enable_capture',
  nova_browser_invalid_url: 'grabber_error_invalid_url_msg',
  nova_browser_script_group: 'settings_integrations_automation',
  nova_browser_script_name: 'sched_list_name_edit',
  nova_browser_script_match: 'set_security_trusted_origins',
  nova_browser_script_source: 'task_description',
  nova_dns_configuration: 'settings_dns_configuration',
  nova_dns_provider: 'settings_dns_provider',
  nova_dns_system_default: 'settings_dns_system_default',
  nova_dns_custom: 'settings_dns_custom',
  nova_dns_custom_label: 'settings_dns_custom_label',
  nova_dns_validate: 'settings_dns_test',
  nova_dns_valid: 'settings_dns_custom_applied',
  nova_dns_invalid: 'settings_dns_test_failed',
  nova_security_privacy: 'settings_security_privacy',
  nova_not_supported: 'task_not_supported',
} as const;

function androidValuesDirectory(language: string): string {
  return language === 'en' ? 'values' : `values-b+${language.replaceAll('-', '+')}`;
}

function escapeXml(value: string): string {
  const escaped = value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\n', '\\n');
  return escaped.replace(/^([@?])/, '\\$1');
}

function formatPlaceholders(value: string): { text: string; formatted: boolean } {
  const names = [...new Set([...value.matchAll(/\{([A-Za-z0-9_]+)\}/g)].map(match => match[1]))];
  if (names.length === 0) return { text: value, formatted: false };

  let text = value;
  names.forEach((name, index) => {
    text = text.replaceAll(`{${name}}`, `%${String(index + 1)}$s`);
  });
  return { text, formatted: true };
}

function buildXml(dictionary: Record<string, string>, language: string): string {
  const entries = Object.entries(RESOURCE_KEYS).map(([resourceName, catalogKey]) => {
    const value = dictionary[catalogKey];
    if (typeof value !== 'string' || value.length === 0) {
      throw new Error(`${language} is missing a non-empty NOVA translation for ${catalogKey}`);
    }
    const rendered = formatPlaceholders(value);
    const formattedAttribute = rendered.formatted ? '' : ' formatted="false"';
    return `    <string name="${resourceName}"${formattedAttribute}>${escapeXml(rendered.text)}</string>`;
  });

  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- Generated by scripts/generate-android-locales.mts. Do not edit manually. -->',
    `<resources><!-- ${language}; ${String(entries.length)} synchronized NOVA strings -->`,
    ...entries,
    '</resources>',
    '',
  ].join('\n');
}

function writeOrCheck(path: string, content: string): void {
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (existing === content) return;
  if (CHECK_ONLY) {
    throw new Error(`Android locale output is stale: ${path}. Run pnpm android:i18n:generate.`);
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
}

async function main(): Promise<void> {
  for (const { value: language } of LANGUAGE_METADATA) {
    const dictionary: unknown = await loadDict(language);
    if (!dictionary) throw new Error(`Could not load NOVA translation dictionary: ${language}`);
    writeOrCheck(
      join(RES_DIR, androidValuesDirectory(language), 'strings.xml'),
      buildXml(dictionary as Record<string, string>, language),
    );
  }

  console.warn(
    `[android:i18n] ${String(LANGUAGE_METADATA.length)} locales synchronized with ${String(Object.keys(RESOURCE_KEYS).length)} Android-visible strings${CHECK_ONLY ? ' (verified)' : ''}.`,
  );
}

await main();
export { RESOURCE_KEYS };
