import type { RuntimeMessage } from '../contracts/messages.schema';
import { NovaExtensionError } from '../core/error-classification';
import { isExtensionUiSender } from './page-scan-policy';
import type { RuntimeMessageSenderLike } from './page-scan-policy';

const UI_ONLY_MESSAGES = new Set<RuntimeMessage['type']>([
  'AUTO_CONNECT',
  'RETRY_CONNECT',
  'RESET_PAIRING',
  'SCAN_PAGE',
  'GET_CANDIDATES',
  'CLEAR_CANDIDATES',
  'SEND_CANDIDATE',
  'SEND_BATCH',
  'RESOLVE_STREAM',
  'SEND_STREAM',
  'GET_OUTBOX_STATUS',
  'RUN_OUTBOX_RETRY',
  'GET_DIAGNOSTICS',
  'GET_SETTINGS',
  'UPDATE_SETTINGS',
  'EXPORT_SETTINGS',
  'IMPORT_SETTINGS',
  'CLEAR_LOCAL_DATA',
  'GET_SITE_RULES',
  'UPSERT_SITE_RULE',
  'DELETE_SITE_RULE',
  'IMPORT_SITE_RULES',
  'EXPORT_SITE_RULES',
  'REQUEST_PERMISSION',
  'GET_PERMISSION_STATUS',
  'PAUSE_TASK',
  'RESUME_TASK',
  'CANCEL_TASK',
  'LIST_TASKS',
  'OPEN_NOVA',
]);

const PASSIVE_MESSAGES = new Set<RuntimeMessage['type']>(['GET_BRIDGE_STATE']);
const BACKGROUND_INTERNAL_MESSAGES = new Set<RuntimeMessage['type']>(['CAPTURE_CONTEXT_MENU']);
// Messages accepted ONLY from a trusted in-page content script (must have a tab id,
// must not be an extension UI surface). SCAN_PAGE stays UI-only by design.
const CONTENT_SCRIPT_MESSAGES = new Set<RuntimeMessage['type']>([
  'OVERLAY_SCAN_PAGE',
  'OVERLAY_REFRESH_CANDIDATES',
  'OVERLAY_SEND_SELECTED',
  'PAGE_TAP_CANDIDATES_FOUND',
  'TAKEOVER_DOWNLOAD_CLICK',
]);

function isBackgroundInternalSender(sender: RuntimeMessageSenderLike | undefined): boolean {
  // Internal background calls usually do not cross runtime messaging. If they ever do,
  // they should not carry a tab URL. Reject page/content-script senders by default.
  return !sender?.tab?.id && !sender?.url;
}

function isTrustedContentScriptSender(sender: RuntimeMessageSenderLike | undefined): boolean {
  // onMessage only delivers same-extension messages, so a sender with a real tab id is
  // our own content script. Reject extension UI surfaces and tab-less senders here.
  const tabId = sender?.tab?.id;
  if (typeof tabId !== 'number' || !Number.isInteger(tabId) || tabId <= 0) return false;
  if (isExtensionUiSender(sender)) return false;
  const url = sender?.url;
  if (!url) return false;
  try {
    const protocol = new URL(url).protocol;
    return protocol === 'http:' || protocol === 'https:';
  } catch {
    return false;
  }
}

export function assertRuntimeMessageAllowed(message: RuntimeMessage, sender: RuntimeMessageSenderLike | undefined): void {
  if (PASSIVE_MESSAGES.has(message.type)) return;

  if (BACKGROUND_INTERNAL_MESSAGES.has(message.type)) {
    if (isBackgroundInternalSender(sender) || isExtensionUiSender(sender)) return;
    throw new NovaExtensionError({
      code: 'PERMISSION_MISSING',
      message: 'Context-menu capture messages are not accepted from page content scripts.',
      retryable: false,
      repairHint: 'Use the browser context menu generated by NOVA Extension.',
    });
  }

  if (UI_ONLY_MESSAGES.has(message.type) && isExtensionUiSender(sender)) return;

  if (CONTENT_SCRIPT_MESSAGES.has(message.type)) {
    if (isTrustedContentScriptSender(sender)) return;
    throw new NovaExtensionError({
      code: 'PERMISSION_MISSING',
      message: `Runtime message ${message.type} is only accepted from a trusted in-page content script.`,
      retryable: false,
      repairHint: 'Use the NOVA popup to scan and send candidates.',
      details: { messageType: message.type, senderUrl: sender?.url, hasTab: Boolean(sender?.tab?.id) },
    });
  }

  throw new NovaExtensionError({
    code: 'PERMISSION_MISSING',
    message: `Runtime message ${message.type} requires a trusted extension UI sender.`,
    retryable: false,
    repairHint: 'Open the extension popup and retry.',
    details: { messageType: message.type, senderUrl: sender?.url, hasTab: Boolean(sender?.tab?.id) },
  });
}
