// Generated by scripts/generate-design-tokens.mjs from nova-design-tokens.json.
pragma Singleton

import QtQuick

QtObject {
    property bool darkMode: true
    property bool highContrast: false
    property bool reducedMotion: false
    property real fontScale: 1.0
    property color accentBase: "#168df7"
    property real densityScale: 1.0
    property int radiusBase: 10

    readonly property color window: highContrast ? (darkMode ? "#000000" : "#ffffff") : (darkMode ? "#0d1015" : "#f4f6f8")
    readonly property color sidebar: highContrast ? (darkMode ? "#050505" : "#f7f7f7") : (darkMode ? "#11151b" : "#ffffff")
    readonly property color surface: highContrast ? (darkMode ? "#0a0a0a" : "#ffffff") : (darkMode ? "#151a21" : "#ffffff")
    readonly property color surfaceHover: highContrast ? (darkMode ? "#202020" : "#e8e8e8") : (darkMode ? "#1b222c" : "#edf2f7")
    readonly property color surfaceSelected: highContrast ? (darkMode ? "#282828" : "#dedede") : (darkMode ? "#202a38" : "#dfe9f8")
    readonly property color surfaceRaised: highContrast ? (darkMode ? "#101010" : "#fafafa") : (darkMode ? "#1a2029" : "#f8fafc")
    readonly property color border: highContrast ? (darkMode ? "#ffffff" : "#000000") : (darkMode ? "#28313d" : "#d9e0e8")
    readonly property color borderStrong: highContrast ? (darkMode ? "#ffffff" : "#000000") : (darkMode ? "#394657" : "#aeb9c6")
    readonly property color textPrimary: highContrast ? (darkMode ? "#ffffff" : "#000000") : (darkMode ? "#f3f6fa" : "#18212c")
    readonly property color textSecondary: highContrast ? (darkMode ? "#f0f0f0" : "#171717") : (darkMode ? "#a8b1bd" : "#4d5b6b")
    readonly property color textMuted: highContrast ? (darkMode ? "#d0d0d0" : "#303030") : (darkMode ? "#7f8b9b" : "#627187")
    readonly property color accent: highContrast ? (darkMode ? "#66a3ff" : "#0047b3") : accentBase
    readonly property color accentMuted: highContrast ? (darkMode ? "#173d70" : "#d5e4ff") : (darkMode ? "#20345a" : "#dce9ff")
    readonly property color success: highContrast ? (darkMode ? "#66ff66" : "#006400") : (darkMode ? "#3fb950" : "#188038")
    readonly property color warning: highContrast ? (darkMode ? "#ffdf66" : "#754c00") : (darkMode ? "#d29922" : "#9a6700")
    readonly property color danger: highContrast ? (darkMode ? "#ff6b6b" : "#b00020") : (darkMode ? "#f85149" : "#c62828")
    readonly property color info: highContrast ? (darkMode ? "#80c7ff" : "#004c99") : (darkMode ? "#58a6ff" : "#0061a4")
    readonly property color focusRing: accent

    readonly property int radiusSmall: Math.max(3, Math.round(radiusBase * 0.8))
    readonly property int radiusMedium: Math.max(5, Math.round(radiusBase * 1.2))
    readonly property int radiusLarge: Math.max(8, Math.round(radiusBase * 1.6))
    readonly property int titleBarHeight: Math.round(56 * Math.max(1.0, fontScale))
    readonly property int navigationCollapsedWidth: Math.round(62 * Math.max(1.0, fontScale))
    readonly property int navigationExpandedWidth: Math.round(206 * Math.max(1.0, fontScale))
    readonly property int detailsWidth: Math.round(356 * Math.max(1.0, fontScale))
    readonly property int customizationWidth: Math.round(320 * Math.max(1.0, fontScale))
    readonly property int commandHeight: Math.round(52 * densityScale * Math.max(1.0, fontScale))
    readonly property int rowHeight: Math.round(54 * densityScale * Math.max(1.0, fontScale))
    readonly property int spaceScreenHorizontal: 20
    readonly property int spaceSection: 24
    readonly property int spaceItemGap: 12
    readonly property int spaceCompactGap: 8

    readonly property int fontTiny: Math.round(9 * fontScale)
    readonly property int fontSmall: Math.round(10 * fontScale)
    readonly property int fontBody: Math.round(14 * fontScale)
    readonly property int fontMedium: Math.round(16 * fontScale)
    readonly property int fontTitle: Math.round(22 * fontScale)

    readonly property int animationFast: reducedMotion ? 0 : 100
    readonly property int animationNormal: reducedMotion ? 0 : 180
}
